include:
  - project: darwinsw/gitlab-pipeline-templates/dotnet-templates
    ref: main
    file: dotnet-library.yml

variables:
  SOLUTION_NAME: "CsvMagic"
  PUBLIC_SITE: "https://darwinsw.gitlab.io/csvmagic.net"
