// Writing
await Examples.Writing.GettingStarted.Run();
await Examples.Writing.CustomOptions.Run();
await Examples.Writing.ReadableProperties.Run();
await Examples.Writing.RecursiveRendering.Run();
await Examples.Writing.RecursiveRenderingWIthFullyQualifiedNames.Run();
await Examples.Writing.CustomRenderersPerType.Run();
await Examples.Writing.CustomRenderersPerProperty.Run();
await Examples.Writing.MixingGlobalAndPropertyRenderers.Run();
// Reading
await Examples.Reading.GettingStarted.Run();
